"""Scryfall keyword catalog (abilities, actions, ability words).

Generated from api.scryfall.com/catalog/* on 2026-05-22.
Regenerate: python scripts/generate_keyword_registry.py
"""

from __future__ import annotations

# (display_name, kind, category)
# kind: ability | action | word
KEYWORD_ENTRIES: tuple[tuple[str, str, str], ...] = (
    ('Absorb', 'ability', 'ability_other'),
    ('Affinity', 'ability', 'ability_other'),
    ('Afflict', 'ability', 'ability_other'),
    ('Afterlife', 'ability', 'ability_other'),
    ('Aftermath', 'ability', 'casting'),
    ('Amplify', 'ability', 'ability_other'),
    ('Annihilator', 'ability', 'ability_other'),
    ('Ascend', 'ability', 'ability_other'),
    ('Assist', 'ability', 'ability_other'),
    ('Augment', 'ability', 'ability_other'),
    ('Aura Swap', 'ability', 'ability_other'),
    ('Awaken', 'ability', 'ability_other'),
    ('Backup', 'ability', 'ability_other'),
    ('Banding', 'ability', 'ability_other'),
    ('Bargain', 'ability', 'ability_other'),
    ('Basic landcycling', 'ability', 'activated'),
    ('Battle Cry', 'ability', 'ability_other'),
    ('Bestow', 'ability', 'casting'),
    ('Blitz', 'ability', 'ability_other'),
    ('Bloodthirst', 'ability', 'ability_other'),
    ('Boast', 'ability', 'ability_other'),
    ('Bushido', 'ability', 'ability_other'),
    ('Buyback', 'ability', 'casting'),
    ('Cascade', 'ability', 'casting'),
    ('Casualty', 'ability', 'ability_other'),
    ('Champion', 'ability', 'ability_other'),
    ('Changeling', 'ability', 'ability_other'),
    ('Choose a background', 'ability', 'ability_other'),
    ('Cipher', 'ability', 'ability_other'),
    ('Cleave', 'ability', 'ability_other'),
    ('Commander ninjutsu', 'ability', 'ability_other'),
    ('Companion', 'ability', 'ability_other'),
    ('Compleated', 'ability', 'ability_other'),
    ('Conspire', 'ability', 'ability_other'),
    ('Convoke', 'ability', 'casting'),
    ('Craft', 'ability', 'ability_other'),
    ('Crew', 'ability', 'activated'),
    ('Cumulative upkeep', 'ability', 'ability_other'),
    ('Cycling', 'ability', 'activated'),
    ('Dash', 'ability', 'ability_other'),
    ('Daybound', 'ability', 'ability_other'),
    ('Deathtouch', 'ability', 'combat_damage'),
    ('Decayed', 'ability', 'ability_other'),
    ('Defender', 'ability', 'combat_passive'),
    ('Delve', 'ability', 'casting'),
    ('Demonstrate', 'ability', 'ability_other'),
    ('Desertwalk', 'ability', 'combat_evasion'),
    ('Dethrone', 'ability', 'ability_other'),
    ('Devoid', 'ability', 'ability_other'),
    ('Devour', 'ability', 'ability_other'),
    ('Disguise', 'ability', 'ability_other'),
    ('Disturb', 'ability', 'ability_other'),
    ("Doctor's companion", 'ability', 'ability_other'),
    ('Double agenda', 'ability', 'ability_other'),
    ('Double strike', 'ability', 'combat_damage'),
    ('Double team', 'ability', 'ability_other'),
    ('Dredge', 'ability', 'ability_other'),
    ('Echo', 'ability', 'ability_other'),
    ('Embalm', 'ability', 'ability_other'),
    ('Emerge', 'ability', 'casting'),
    ('Enchant', 'ability', 'ability_other'),
    ('Encore', 'ability', 'ability_other'),
    ('Enlist', 'ability', 'ability_other'),
    ('Entwine', 'ability', 'casting'),
    ('Epic', 'ability', 'ability_other'),
    ('Equip', 'ability', 'activated'),
    ('Escalate', 'ability', 'ability_other'),
    ('Escape', 'ability', 'casting'),
    ('Eternalize', 'ability', 'ability_other'),
    ('Evoke', 'ability', 'ability_other'),
    ('Evolve', 'ability', 'ability_other'),
    ('Exalted', 'ability', 'ability_other'),
    ('Exhaust', 'ability', 'ability_other'),
    ('Exploit', 'ability', 'ability_other'),
    ('Extort', 'ability', 'ability_other'),
    ('Fabricate', 'ability', 'ability_other'),
    ('Fading', 'ability', 'ability_other'),
    ('Fear', 'ability', 'combat_evasion'),
    ('Firebending', 'ability', 'ability_other'),
    ('First strike', 'ability', 'combat_damage'),
    ('Flanking', 'ability', 'ability_other'),
    ('Flash', 'ability', 'timing'),
    ('Flashback', 'ability', 'casting'),
    ('Flying', 'ability', 'combat_evasion'),
    ('For Mirrodin!', 'ability', 'ability_other'),
    ('Forecast', 'ability', 'ability_other'),
    ('Forestcycling', 'ability', 'activated'),
    ('Forestwalk', 'ability', 'combat_evasion'),
    ('Foretell', 'ability', 'casting'),
    ('Fortify', 'ability', 'ability_other'),
    ('Freerunning', 'ability', 'casting'),
    ('Frenzy', 'ability', 'ability_other'),
    ('Friends forever', 'ability', 'ability_other'),
    ('Fuse', 'ability', 'ability_other'),
    ('Gift', 'ability', 'ability_other'),
    ('Graft', 'ability', 'ability_other'),
    ('Gravestorm', 'ability', 'ability_other'),
    ('Harmonize', 'ability', 'ability_other'),
    ('Haste', 'ability', 'timing'),
    ('Haunt', 'ability', 'ability_other'),
    ('Hexproof', 'ability', 'targeting'),
    ('Hexproof from', 'ability', 'ability_other'),
    ('Hidden agenda', 'ability', 'ability_other'),
    ('Hideaway', 'ability', 'ability_other'),
    ('Horsemanship', 'ability', 'ability_other'),
    ('Impending', 'ability', 'ability_other'),
    ('Improvise', 'ability', 'casting'),
    ('Increment', 'ability', 'ability_other'),
    ('Indestructible', 'ability', 'survival'),
    ('Infect', 'ability', 'counters'),
    ('Ingest', 'ability', 'ability_other'),
    ('Intensity', 'ability', 'ability_other'),
    ('Intimidate', 'ability', 'combat_evasion'),
    ('Islandcycling', 'ability', 'activated'),
    ('Islandwalk', 'ability', 'combat_evasion'),
    ('Job select', 'ability', 'ability_other'),
    ('Jump-start', 'ability', 'casting'),
    ('Kicker', 'ability', 'casting'),
    ('Landcycling', 'ability', 'activated'),
    ('Landwalk', 'ability', 'combat_evasion'),
    ('Legendary landwalk', 'ability', 'combat_evasion'),
    ('Level Up', 'ability', 'activated'),
    ('Lifelink', 'ability', 'combat_damage'),
    ('Living metal', 'ability', 'ability_other'),
    ('Living weapon', 'ability', 'ability_other'),
    ('Madness', 'ability', 'casting'),
    ('Max speed', 'ability', 'ability_other'),
    ('Mayhem', 'ability', 'ability_other'),
    ('Megamorph', 'ability', 'ability_other'),
    ('Melee', 'ability', 'ability_other'),
    ('Menace', 'ability', 'combat_evasion'),
    ('Mentor', 'ability', 'ability_other'),
    ('Miracle', 'ability', 'casting'),
    ('Mobilize', 'ability', 'ability_other'),
    ('Modular', 'ability', 'counters'),
    ('More Than Meets the Eye', 'ability', 'ability_other'),
    ('Morph', 'ability', 'ability_other'),
    ('Mountaincycling', 'ability', 'activated'),
    ('Mountainwalk', 'ability', 'combat_evasion'),
    ('Multikicker', 'ability', 'ability_other'),
    ('Mutate', 'ability', 'casting'),
    ('Myriad', 'ability', 'ability_other'),
    ('Nightbound', 'ability', 'ability_other'),
    ('Ninjutsu', 'ability', 'ability_other'),
    ('Nonbasic landwalk', 'ability', 'combat_evasion'),
    ('Offering', 'ability', 'ability_other'),
    ('Offspring', 'ability', 'ability_other'),
    ('Outlast', 'ability', 'ability_other'),
    ('Overload', 'ability', 'casting'),
    ('Paradigm', 'ability', 'ability_other'),
    ('Partner', 'ability', 'ability_other'),
    ('Partner with', 'ability', 'ability_other'),
    ('Persist', 'ability', 'counters'),
    ('Phasing', 'ability', 'ability_other'),
    ('Plainscycling', 'ability', 'activated'),
    ('Plainswalk', 'ability', 'combat_evasion'),
    ('Poisonous', 'ability', 'ability_other'),
    ('Protection', 'ability', 'targeting'),
    ('Prototype', 'ability', 'ability_other'),
    ('Provoke', 'ability', 'ability_other'),
    ('Prowess', 'ability', 'ability_other'),
    ('Prowl', 'ability', 'ability_other'),
    ('Rampage', 'ability', 'ability_other'),
    ('Ravenous', 'ability', 'ability_other'),
    ('Reach', 'ability', 'combat_evasion'),
    ('Read Ahead', 'ability', 'ability_other'),
    ('Rebound', 'ability', 'ability_other'),
    ('Reconfigure', 'ability', 'ability_other'),
    ('Recover', 'ability', 'ability_other'),
    ('Reinforce', 'ability', 'ability_other'),
    ('Renown', 'ability', 'ability_other'),
    ('Replicate', 'ability', 'casting'),
    ('Retrace', 'ability', 'casting'),
    ('Riot', 'ability', 'ability_other'),
    ('Ripple', 'ability', 'ability_other'),
    ('Saddle', 'ability', 'ability_other'),
    ('Scavenge', 'ability', 'ability_other'),
    ('Shadow', 'ability', 'combat_evasion'),
    ('Shroud', 'ability', 'targeting'),
    ('Skulk', 'ability', 'ability_other'),
    ('Slivercycling', 'ability', 'activated'),
    ('Sneak', 'ability', 'casting'),
    ('Solved', 'ability', 'ability_other'),
    ('Soulbond', 'ability', 'ability_other'),
    ('Soulshift', 'ability', 'ability_other'),
    ('Specialize', 'ability', 'ability_other'),
    ('Spectacle', 'ability', 'ability_other'),
    ('Splice', 'ability', 'ability_other'),
    ('Split second', 'ability', 'ability_other'),
    ('Spree', 'ability', 'casting'),
    ('Squad', 'ability', 'ability_other'),
    ('Station', 'ability', 'ability_other'),
    ('Storm', 'ability', 'casting'),
    ('Sunburst', 'ability', 'ability_other'),
    ('Surge', 'ability', 'ability_other'),
    ('Suspend', 'ability', 'casting'),
    ('Swampcycling', 'ability', 'activated'),
    ('Swampwalk', 'ability', 'combat_evasion'),
    ('Tiered', 'ability', 'ability_other'),
    ('Toxic', 'ability', 'ability_other'),
    ('Training', 'ability', 'ability_other'),
    ('Trample', 'ability', 'combat_damage'),
    ('Transfigure', 'ability', 'ability_other'),
    ('Transmute', 'ability', 'ability_other'),
    ('Tribute', 'ability', 'ability_other'),
    ('Typecycling', 'ability', 'activated'),
    ('Umbra armor', 'ability', 'ability_other'),
    ('Undaunted', 'ability', 'ability_other'),
    ('Undying', 'ability', 'counters'),
    ('Unearth', 'ability', 'activated'),
    ('Unleash', 'ability', 'ability_other'),
    ('Vanishing', 'ability', 'ability_other'),
    ('Vigilance', 'ability', 'combat_passive'),
    ('Ward', 'ability', 'targeting'),
    ('Warp', 'ability', 'ability_other'),
    ('Web-slinging', 'ability', 'ability_other'),
    ('Wither', 'ability', 'counters'),
    ('Wizardcycling', 'ability', 'activated'),
    ('Abandon', 'action', 'action'),
    ('Activate', 'action', 'action'),
    ('Adapt', 'action', 'action'),
    ('Airbend', 'action', 'action'),
    ('Amass', 'action', 'action'),
    ('Assemble', 'action', 'action'),
    ('Attach', 'action', 'action'),
    ('Behold', 'action', 'action'),
    ('Blight', 'action', 'action'),
    ('Bolster', 'action', 'action'),
    ('Cast', 'action', 'action'),
    ('Clash', 'action', 'action'),
    ('Cloak', 'action', 'action'),
    ('Collect evidence', 'action', 'action'),
    ('Conjure', 'action', 'action'),
    ('Connive', 'action', 'action'),
    ('Convert', 'action', 'action'),
    ('Counter', 'action', 'action'),
    ('Create', 'action', 'action'),
    ('Destroy', 'action', 'action'),
    ('Detain', 'action', 'action'),
    ('Discard', 'action', 'action'),
    ('Discover', 'action', 'action'),
    ('Double', 'action', 'action'),
    ('Earthbend', 'action', 'action'),
    ('Endure', 'action', 'action'),
    ('Exchange', 'action', 'action'),
    ('Exert', 'action', 'action'),
    ('Exile', 'action', 'action'),
    ('Explore', 'action', 'action'),
    ('Fateseal', 'action', 'action'),
    ('Fight', 'action', 'action'),
    ('Food', 'action', 'action'),
    ('Forage', 'action', 'action'),
    ('Goad', 'action', 'action'),
    ('Harness', 'action', 'action'),
    ('Heist', 'action', 'action'),
    ('Incubate', 'action', 'action'),
    ('Investigate', 'action', 'action'),
    ('Learn', 'action', 'action'),
    ('Manifest', 'action', 'action'),
    ('Manifest dread', 'action', 'action'),
    ('Meld', 'action', 'action'),
    ('Mill', 'action', 'action'),
    ('Monstrosity', 'action', 'action'),
    ('Open an Attraction', 'action', 'action'),
    ('Planeswalk', 'action', 'action'),
    ('Play', 'action', 'action'),
    ('Plot', 'action', 'action'),
    ('Populate', 'action', 'action'),
    ('Prepared', 'action', 'action'),
    ('Proliferate', 'action', 'action'),
    ('Regenerate', 'action', 'action'),
    ('Reveal', 'action', 'action'),
    ('Role token', 'action', 'action'),
    ('Roll to Visit Your Attractions', 'action', 'action'),
    ('Sacrifice', 'action', 'action'),
    ('Scry', 'action', 'action'),
    ('Seek', 'action', 'action'),
    ('Set in motion', 'action', 'action'),
    ('Shuffle', 'action', 'action'),
    ('Support', 'action', 'action'),
    ('Surveil', 'action', 'action'),
    ('Suspect', 'action', 'action'),
    ('Tap', 'action', 'action'),
    ('Time Travel', 'action', 'action'),
    ('Transform', 'action', 'action'),
    ('Treasure', 'action', 'action'),
    ('Untap', 'action', 'action'),
    ('Venture into the dungeon', 'action', 'action'),
    ('Vote', 'action', 'action'),
    ('Waterbend', 'action', 'action'),
    ('Adamant', 'word', 'ability_word'),
    ('Addendum', 'word', 'ability_word'),
    ('Alliance', 'word', 'ability_word'),
    ('Battalion', 'word', 'ability_word'),
    ('Bloodrush', 'word', 'ability_word'),
    ('Celebration', 'word', 'ability_word'),
    ('Channel', 'word', 'ability_word'),
    ('Chroma', 'word', 'ability_word'),
    ('Cohort', 'word', 'ability_word'),
    ('Constellation', 'word', 'ability_word'),
    ('Converge', 'word', 'ability_word'),
    ('Corrupted', 'word', 'ability_word'),
    ("Council's dilemma", 'word', 'ability_word'),
    ('Coven', 'word', 'ability_word'),
    ('Delirium', 'word', 'ability_word'),
    ('Descend', 'word', 'ability_word'),
    ('Disappear', 'word', 'ability_word'),
    ('Domain', 'word', 'ability_word'),
    ('Eerie', 'word', 'ability_word'),
    ('Eminence', 'word', 'ability_word'),
    ('Enrage', 'word', 'ability_word'),
    ('Fateful hour', 'word', 'ability_word'),
    ('Fathomless descent', 'word', 'ability_word'),
    ('Ferocious', 'word', 'ability_word'),
    ('Flurry', 'word', 'ability_word'),
    ('Formidable', 'word', 'ability_word'),
    ('Grandeur', 'word', 'ability_word'),
    ('Hellbent', 'word', 'ability_word'),
    ("Hero's Reward", 'word', 'ability_word'),
    ('Heroic', 'word', 'ability_word'),
    ('Imprint', 'word', 'ability_word'),
    ('Infusion', 'word', 'ability_word'),
    ('Inspired', 'word', 'ability_word'),
    ('Join forces', 'word', 'ability_word'),
    ('Kinfall', 'word', 'ability_word'),
    ('Kinship', 'word', 'ability_word'),
    ('Landfall', 'word', 'ability_word'),
    ('Landship', 'word', 'ability_word'),
    ('Legacy', 'word', 'ability_word'),
    ('Lieutenant', 'word', 'ability_word'),
    ('Magecraft', 'word', 'ability_word'),
    ('Metalcraft', 'word', 'ability_word'),
    ('Morbid', 'word', 'ability_word'),
    ('Opus', 'word', 'ability_word'),
    ('Pack tactics', 'word', 'ability_word'),
    ('Paradox', 'word', 'ability_word'),
    ('Parley', 'word', 'ability_word'),
    ('Radiance', 'word', 'ability_word'),
    ('Raid', 'word', 'ability_word'),
    ('Rally', 'word', 'ability_word'),
    ('Renew', 'word', 'ability_word'),
    ('Repartee', 'word', 'ability_word'),
    ('Revolt', 'word', 'ability_word'),
    ('Secret council', 'word', 'ability_word'),
    ('Spell mastery', 'word', 'ability_word'),
    ('Start your engines!', 'word', 'ability_word'),
    ('Strive', 'word', 'ability_word'),
    ('Survival', 'word', 'ability_word'),
    ('Sweep', 'word', 'ability_word'),
    ('Teamwork', 'word', 'ability_word'),
    ('Tempting offer', 'word', 'ability_word'),
    ('Threshold', 'word', 'ability_word'),
    ('Underdog', 'word', 'ability_word'),
    ('Undergrowth', 'word', 'ability_word'),
    ('Valiant', 'word', 'ability_word'),
    ('Vivid', 'word', 'ability_word'),
    ('Void', 'word', 'ability_word'),
    ('Will of the council', 'word', 'ability_word'),
    ('Will of the Planeswalkers', 'word', 'ability_word'),
)

SCRYFALL_KEYWORD_COUNT = 359
